### ISSUE TITLE
[IDEA] Add Russian Translations :ru:

### ISSUE THREAD

**Issue by neoaboy** [easyintent/quickref#1]
Hello.
Your app is so useful, but very lacking Russian. If you want, i can help with translations.
What do you think about it?

**Comment by bangun** [comment]
Hi, thanks for your interest.

I am sorry, but multi language is not supported by current architecture.

Yes, it is possible to translate application labels under `res/values/` directory.
But the content itself is just a single SQLite database inside `assets` directory.

Supporting multi language require changes how the SQLite database structured and loaded.

**Comment by neoaboy** [comment]
Thanks for your reply.

Do you plan these changes? Or multilanguage support so will remain unrealized?
I am a junior C++ developer and Java never wrote, but if need, I will learn essential and help you.

**Comment by bangun** [comment]
Hi, really appreciate your offer!

> Do you plan these changes? Or multilanguage support so will remain unrealized?

Unfortunately, yes. For simplicity, it will only available in English.

Other contributions are welcome though :)
