### ISSUE TITLE
Form to add references

### ISSUE THREAD

**Issue by farisachugthai** [easyintent/quickref#2]
Just downloaded the app today and was wondering if a new feature could be implemented allowing a user to add in their own personal references. Thanks!

**Comment by farisachugthai** [comment]
Also wanted to say that the app is great so far and really nails down all the commands I end up googling when starting a new repo!

**Comment by bangun** [comment]
> Also wanted to say that the app is great so far and really nails down all the commands I end up googling when starting a new repo!

Thanks, really glad to hear that!

> Just downloaded the app today and was wondering if a new feature could be implemented allowing a user to add in their own personal references. Thanks!

Interesting idea

For such feature, most user will expect the collection of personal reference can be synchronized between device and persist between app install-uninstall cycle. It require online synchronization which currently does not align with some of application goals (completely offline, no permissions)

Nevertheless it is an interesting idea, maybe when writing new application I will consider that feature. Don't hold your breath though 😉

In the meantime, I recommend to use Google Keep to write your personal reference as a workaround

Thanks again!
