### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [easyintent/quickref#4]
Hi @easyintent

Since this app is Apache v2 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and some of us could probably use your app a lot :)

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you? The first step will be to open a RFP [here](https://gitlab.com/fdroid/rfp/issues).

**Comment by bangun** [comment]
Adding to F-droid would be great :)

But currently I don't have much free time for actually doing that... it is ok if someone else including it to F-Droid and I would thankful for that :)

**Comment by Poussinou** [comment]
Here you go with the RFP: https://gitlab.com/fdroid/rfp/issues/1220

**Comment by IzzySoft** [comment]
@bangun would you find a little time to establish [Fastlane file structure](https://gitlab.com/snippets/1895688) in your repo? That would be much appreciated! That way you can keep summary/description updated without the need of additional Merge Requests each time, and also provide screenshots. And you can use these very same structures for publishing your app on Play.

**Comment by bangun** [comment]
@Poussinou thanks for submitting, really appreciate it :)

@IzzySoft I don't use fastlane tools, but I will read up and consider including it if that help deployment to F-droid

**Comment by bangun** [comment]
@IzzySoft basic fastlane file structure has been added to [dev](/easyintent/quickref/tree/dev) branch.
Let me know if something missing.

If everything OK, I will merge it to `master` and create new tag.

**Comment by IzzySoft** [comment]
@bangun that looks finee, thanks! Just a pointer: in `full_description.txt`, every line-brak will be replaced by `<br>\n`, so "empty lines" create quite a gap. Just in case you bother later, I thought to tell you earlier :wink:

Let me know when Fastlane is covered by a tag, then I can push the RFP further.

**Comment by bangun** [comment]
@IzzySoft fastlane already covered by `0.6.0` tag and the extra empty line from `full_description.txt` was removed, thanks

**Comment by IzzySoft** [comment]
Thanks @bangun – RFP updated and "kicked upstairs" (to our packagers). Would be great if you also could add changelogs (doing so via fastlane would kick your app to the "featured" (aka "new") screen of the F-Droid app on arrival). Not a requirement, though – but would be "icing on the cake" :wink:

**Comment by bangun** [comment]
many thanks for anyone involved to make it available on F-droid!
