### ISSUE TITLE
just a note for developer

### ISSUE THREAD

**Issue by ret394** [easyintent/quickref#7]
Didn't get the time for it before, but if you need to discuss anything related to development, coronavirus and related topics, feel free to ask me. Reach out to me at https://github.com/ret394/jubilant-broccoli/issues/new and close the issue.
Sorry if you did try to contact me, I must have missed it.

And don't get stressed, the corona-virus crisis will improve soon, depending on your location.

And to give you a teaser of the advice. **The security issues with Android apps are not the fault of the Android developers.**

thanks. have a nice day. take care.

[ret394](https://github.com/ret394)

**Comment by bangun** [comment]
Thank you for giving encouragement and offering place for discussion 🙂
